import { Code, Brain, Palette, Building, Wrench, MessageCircle, Cloud, Workflow, type LucideIcon } from "lucide-react"

export type Program = {
  title: string
  description: string
  duration: string
  level: "Beginner" | "Intermediate" | "Advanced"
  category: string
  image: string
  icon: LucideIcon
  color: string
}

export const programs: Program[] = [
  // CADD NEST Courses (high-level)
  {
    title: "Civil CADD",
    description: "Drafting and design for civil engineering projects using CADD tools.",
    duration: "12 weeks",
    level: "Intermediate",
    category: "CADD NEST Courses",
    image: "/civil-cad-engineering.png",
    icon: Wrench,
    color: "from-slate-500 to-gray-600",
  },
  {
    title: "Mechanical CADD",
    description: "3D modeling and technical documentation for mechanical designs.",
    duration: "14 weeks",
    level: "Intermediate",
    category: "CADD NEST Courses",
    image: "/mechanical-cad-design.png",
    icon: Wrench,
    color: "from-red-500 to-orange-600",
  },
  {
    title: "Architectural CADD",
    description: "Architectural drafting, 3D modeling, and visualization workflows.",
    duration: "12 weeks",
    level: "Intermediate",
    category: "CADD NEST Courses",
    image: "/images/courses/architectural-cadd.jpg",
    icon: Wrench,
    color: "from-yellow-500 to-amber-600",
  },
  {
    title: "Project Planning And Management",
    description: "Scheduling, resource planning, and project controls for engineering projects.",
    duration: "10 weeks",
    level: "Intermediate",
    category: "CADD NEST Courses",
    image: "/images/courses/project-planning-management.jpg",
    icon: Wrench,
    color: "from-emerald-500 to-teal-600",
  },
  {
    title: "Interior Design (CADD NEST)",
    description: "Space planning and interior visualization using CAD tools.",
    duration: "14 weeks",
    level: "Intermediate",
    category: "CADD NEST Courses",
    image: "/interior-design-planning.png",
    icon: Wrench,
    color: "from-purple-500 to-pink-600",
  },

  // IT Courses (from screenshots)
  {
    title: "Full Stack Development (Institute Program)",
    description: "End‑to‑end web app development with modern stacks.",
    duration: "18 weeks",
    level: "Intermediate",
    category: "IT Courses",
    image: "/images/courses/full-stack-institute.jpg",
    icon: Code,
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "Full Stack Data Science Course",
    description: "Data analysis, ML pipelines, deployment, and MLOps foundations.",
    duration: "20 weeks",
    level: "Advanced",
    category: "IT Courses",
    image: "/data-science-python.png",
    icon: Brain,
    color: "from-cyan-500 to-blue-600",
  },
  {
    title: "Software Testing Programs",
    description: "Manual and automated testing with industry-standard tools.",
    duration: "10 weeks",
    level: "Beginner",
    category: "IT Courses",
    image: "/images/courses/software-testing.jpg",
    icon: Code,
    color: "from-rose-500 to-pink-600",
  },
  {
    title: "IT Individual Courses",
    description: "Pick-and-choose modules across programming, cloud, and tools.",
    duration: "Self-paced",
    level: "Beginner",
    category: "IT Courses",
    image: "/images/courses/it-individual.jpg",
    icon: Code,
    color: "from-teal-500 to-emerald-600",
  },
  {
    title: "Cloud Computing",
    description: "Core cloud services, architecture, and deployments on AWS/Azure/GCP.",
    duration: "12 weeks",
    level: "Intermediate",
    category: "Cloud & DevOps",
    image: "/placeholder.svg?height=200&width=300",
    icon: Cloud,
    color: "from-sky-500 to-indigo-600",
  },
  {
    title: "DevOps",
    description: "CI/CD pipelines, containers, IaC (Terraform), and observability.",
    duration: "12 weeks",
    level: "Intermediate",
    category: "Cloud & DevOps",
    image: "/placeholder.svg?height=200&width=300",
    icon: Workflow,
    color: "from-teal-500 to-emerald-600",
  },

  // ACCOUNTING COURSES (from screenshots)
  {
    title: "MS Office Course",
    description: "Master Word, Excel, PowerPoint, and Outlook for productivity.",
    duration: "8 weeks",
    level: "Beginner",
    category: "ACCOUNTING COURSES",
    image: "/ms-office-suite-training.png",
    icon: Building,
    color: "from-orange-500 to-red-600",
  },
  {
    title: "Tally Training Institute in Bangalore",
    description: "Practical Tally Prime training for accounting and GST.",
    duration: "10 weeks",
    level: "Intermediate",
    category: "ACCOUNTING COURSES",
    image: "/tally-prime-accounting.png",
    icon: Building,
    color: "from-purple-500 to-indigo-600",
  },
  {
    title: "Advanced Excel",
    description: "Formulas, pivots, dashboards, and analytics with Excel.",
    duration: "6 weeks",
    level: "Intermediate",
    category: "ACCOUNTING COURSES",
    image: "/advanced-excel-training.png",
    icon: Building,
    color: "from-green-500 to-teal-600",
  },
  {
    title: "SAP",
    description: "Enterprise resource planning with SAP modules and processes.",
    duration: "16 weeks",
    level: "Advanced",
    category: "ACCOUNTING COURSES",
    image: "/sap-enterprise-software.png",
    icon: Building,
    color: "from-emerald-500 to-green-600",
  },
  {
    title: "VBA Macro’s",
    description: "Automate Excel workflows using VBA macros.",
    duration: "8 weeks",
    level: "Advanced",
    category: "ACCOUNTING COURSES",
    image: "/vba-macros-programming.png",
    icon: Building,
    color: "from-blue-500 to-cyan-600",
  },

  // ANIMATION STUDIOS
  {
    title: "Animation Studios",
    description: "Fundamentals of multimedia, 2D/3D animation pipelines, and tools.",
    duration: "12 weeks",
    level: "Beginner",
    category: "ANIMATION STUDIOS",
    image: "/images/courses/animation-studios.jpg",
    icon: Palette,
    color: "from-pink-500 to-rose-600",
  },

  // Handwriting & Speed Writing
  {
    title: "Handwriting Courses",
    description: "Improve handwriting clarity, speed, and presentation.",
    duration: "4 weeks",
    level: "Beginner",
    category: "Handwriting Courses",
    image: "/images/courses/handwriting.jpg",
    icon: MessageCircle,
    color: "from-amber-500 to-orange-600",
  },
  {
    title: "Speed Writing",
    description: "Techniques to enhance writing speed while maintaining legibility.",
    duration: "3 weeks",
    level: "Beginner",
    category: "Speed Writing",
    image: "/images/courses/speed-writing.jpg",
    icon: MessageCircle,
    color: "from-yellow-500 to-amber-600",
  },

  // Calligraphy
  {
    title: "Calligraphy",
    description: "Beautiful lettering styles and decorative scripts.",
    duration: "6 weeks",
    level: "Beginner",
    category: "Calligraphy Courses",
    image: "/calligraphy-art-writing.png",
    icon: Palette,
    color: "from-amber-500 to-orange-600",
  },

  // Spoken English Training
  {
    title: "Spoken English",
    description: "Fluency, grammar, and conversational practice to speak confidently.",
    duration: "10 weeks",
    level: "Beginner",
    category: "Spoken English Training",
    image: "/spoken-english-communication.png",
    icon: MessageCircle,
    color: "from-teal-500 to-cyan-600",
  },
  {
    title: "Communication Skills",
    description: "Public speaking, presentation, and interpersonal communication.",
    duration: "8 weeks",
    level: "Beginner",
    category: "Spoken English Training",
    image: "/images/courses/communication-skills.jpg",
    icon: MessageCircle,
    color: "from-indigo-500 to-purple-600",
  },
  {
    title: "Best Soft Skills Course",
    description: "Teamwork, leadership, problem-solving, and workplace etiquette.",
    duration: "8 weeks",
    level: "Beginner",
    category: "Spoken English Training",
    image: "/images/courses/soft-skills.jpg",
    icon: MessageCircle,
    color: "from-emerald-500 to-teal-600",
  },
  {
    title: "Best Interview Skills",
    description: "Interview preparation, resume refinement, and mock interviews.",
    duration: "4 weeks",
    level: "Beginner",
    category: "Spoken English Training",
    image: "/images/courses/interview-skills.jpg",
    icon: MessageCircle,
    color: "from-red-500 to-rose-600",
  },

  // Designing & Development (from screenshots)
  {
    title: "Web Development Course",
    description: "Build responsive, accessible websites with modern web standards.",
    duration: "12 weeks",
    level: "Beginner",
    category: "Designing & Development",
    image: "/web-design-development.png",
    icon: Code,
    color: "from-pink-500 to-rose-600",
  },
  {
    title: "E‑Commerce Course",
    description: "Create and scale online stores with payments and logistics.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Designing & Development",
    image: "/images/courses/ecommerce.jpg",
    icon: Code,
    color: "from-purple-500 to-indigo-600",
  },
  {
    title: "Android App Development Course",
    description: "Native Android apps with Java/Kotlin and modern tooling.",
    duration: "14 weeks",
    level: "Intermediate",
    category: "Designing & Development",
    image: "/android-app-development.png",
    icon: Code,
    color: "from-green-500 to-teal-600",
  },
  {
    title: "Graphic & Web Design Course",
    description: "Design systems, typography, and visual communication for the web.",
    duration: "12 weeks",
    level: "Beginner",
    category: "Designing & Development",
    image: "/graphic-design-creative.png",
    icon: Palette,
    color: "from-blue-500 to-indigo-600",
  },

  // Digital Marketing Courses (extra programs)
  {
    title: "Professional in Digital Marketing",
    description: "End-to-end digital marketing with SEO, SEM, SMM, email and analytics.",
    duration: "12 weeks",
    level: "Beginner",
    category: "Digital Marketing Courses",
    image: "/digital-marketing-strategy.png",
    icon: Palette,
    color: "from-green-500 to-emerald-600",
  },
  {
    title: "Masters in Digital Marketing",
    description: "Advanced planning, automation, growth marketing and analytics.",
    duration: "20 weeks",
    level: "Advanced",
    category: "Digital Marketing Courses",
    image: "/digital-marketing-strategy.png",
    icon: Palette,
    color: "from-cyan-500 to-blue-600",
  },
  {
    title: "Digital Marketing in Kannada",
    description: "SEO, SEM, SMM, and analytics delivered in Kannada.",
    duration: "10 weeks",
    level: "Beginner",
    category: "Digital Marketing Courses",
    image: "/digital-marketing-strategy.png",
    icon: Palette,
    color: "from-green-500 to-emerald-600",
  },
  {
    title: "Digital Marketing Courses in English",
    description: "Plan and execute digital campaigns with measurable ROI.",
    duration: "10 weeks",
    level: "Beginner",
    category: "Digital Marketing Courses",
    image: "/digital-marketing-strategy.png",
    icon: Palette,
    color: "from-cyan-500 to-blue-600",
  },

  // Engineering & CAD — Electrical CADD modules
  {
    title: "AutoCAD Electrical",
    description: "Electrical CAD drafting for circuits, panels, and schematics.",
    duration: "6 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/autocad-electrical.jpg",
    icon: Wrench,
    color: "from-amber-500 to-orange-600",
  },
  {
    title: "Revit MEP",
    description: "BIM for mechanical, electrical, and plumbing coordination.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/revit-mep.jpg",
    icon: Wrench,
    color: "from-teal-500 to-cyan-600",
  },

  // Engineering & CAD — Mechanical CADD modules
  {
    title: "Autocad Mechanical",
    description: "2D/3D drafting for mechanical parts and assemblies.",
    duration: "6 weeks",
    level: "Beginner",
    category: "Engineering & CAD",
    image: "/images/courses/autocad-mechanical.jpg",
    icon: Wrench,
    color: "from-slate-500 to-gray-600",
  },
  {
    title: "Catia",
    description: "Parametric modeling and surface design in CATIA.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/catia.jpg",
    icon: Wrench,
    color: "from-violet-500 to-purple-600",
  },
  {
    title: "Creo",
    description: "Product design and simulation using Creo.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/creo.jpg",
    icon: Wrench,
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "Ansys",
    description: "Finite element analysis for structural/thermal problems.",
    duration: "8 weeks",
    level: "Advanced",
    category: "Engineering & CAD",
    image: "/images/courses/ansys.jpg",
    icon: Wrench,
    color: "from-red-500 to-rose-600",
  },
  {
    title: "GD&T",
    description: "Geometric Dimensioning and Tolerancing essentials.",
    duration: "4 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/gdt.jpg",
    icon: Wrench,
    color: "from-amber-500 to-orange-600",
  },
  {
    title: "Hypermesh",
    description: "High-performance meshing for CAE workflows.",
    duration: "6 weeks",
    level: "Advanced",
    category: "Engineering & CAD",
    image: "/images/courses/hypermesh.jpg",
    icon: Wrench,
    color: "from-fuchsia-500 to-pink-600",
  },
  {
    title: "NX CAD",
    description: "Siemens NX for product design.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/nx-cad.jpg",
    icon: Wrench,
    color: "from-cyan-500 to-blue-600",
  },
  {
    title: "NX CAM",
    description: "Computer-aided manufacturing with toolpaths in NX.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/nx-cam.jpg",
    icon: Wrench,
    color: "from-emerald-500 to-green-600",
  },
  {
    title: "HVAC Design",
    description: "Heating, ventilation, and air conditioning system design.",
    duration: "6 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/hvac-design.jpg",
    icon: Wrench,
    color: "from-sky-500 to-blue-600",
  },
  {
    title: "Inventor",
    description: "Autodesk Inventor for mechanical design.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/inventor.jpg",
    icon: Wrench,
    color: "from-amber-500 to-orange-600",
  },
  {
    title: "Solidworks",
    description: "Solid modeling, assemblies, and drawings in SolidWorks.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/solidworks.jpg",
    icon: Wrench,
    color: "from-rose-500 to-pink-600",
  },
  {
    title: "Fusion 360",
    description: "CAD/CAM/CAE workflows with Fusion 360.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/fusion-360.jpg",
    icon: Wrench,
    color: "from-orange-500 to-red-600",
  },

  // Engineering & CAD — Civil CADD modules
  {
    title: "AutoCAD Civil",
    description: "CAD for civil layouts, profiles, and grading.",
    duration: "6 weeks",
    level: "Beginner",
    category: "Engineering & CAD",
    image: "/images/courses/autocad-civil.jpg",
    icon: Wrench,
    color: "from-slate-500 to-gray-600",
  },
  {
    title: "Revit Architecture",
    description: "BIM modeling for architectural projects.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/revit-architecture.jpg",
    icon: Wrench,
    color: "from-purple-500 to-indigo-600",
  },
  {
    title: "Revit Structure",
    description: "Structural modeling and documentation in Revit.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-rose-500 to-pink-600",
  },
  {
    title: "SketchUp",
    description: "Fast 3D modeling for architecture and interiors.",
    duration: "4 weeks",
    level: "Beginner",
    category: "Engineering & CAD",
    image: "/images/courses/sketchup.jpg",
    icon: Wrench,
    color: "from-green-500 to-emerald-600",
  },
  {
    title: "V-Ray",
    description: "Photorealistic rendering with V-Ray.",
    duration: "4 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/vray.jpg",
    icon: Wrench,
    color: "from-yellow-500 to-amber-600",
  },
  {
    title: "ETABS",
    description: "Structural analysis and design using ETABS.",
    duration: "6 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/etabs.jpg",
    icon: Wrench,
    color: "from-cyan-500 to-blue-600",
  },
  {
    title: "3ds Max",
    description: "Visualization and animation with 3ds Max.",
    duration: "6 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/3ds-max.jpg",
    icon: Wrench,
    color: "from-indigo-500 to-violet-600",
  },
  {
    title: "STAAD.Pro",
    description: "Structural analysis and design in STAAD.",
    duration: "6 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/staad-pro.jpg",
    icon: Wrench,
    color: "from-fuchsia-500 to-pink-600",
  },
  {
    title: "Lumion",
    description: "Real‑time architectural visualization.",
    duration: "4 weeks",
    level: "Beginner",
    category: "Engineering & CAD",
    image: "/images/courses/lumion.jpg",
    icon: Wrench,
    color: "from-emerald-500 to-teal-600",
  },
  {
    title: "BIM 360",
    description: "Cloud collaboration and coordination for BIM projects.",
    duration: "4 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/bim-360.jpg",
    icon: Wrench,
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "Quantity Takeoff",
    description: "Estimations and BOQs from drawings and models.",
    duration: "4 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/quantity-takeoff.jpg",
    icon: Wrench,
    color: "from-amber-500 to-orange-600",
  },
  {
    title: "MS Project (MSP)",
    description: "Project scheduling with Microsoft Project.",
    duration: "4 weeks",
    level: "Beginner",
    category: "Engineering & CAD",
    image: "/images/courses/ms-project.jpg",
    icon: Wrench,
    color: "from-sky-500 to-blue-600",
  },
  {
    title: "Primavera",
    description: "Advanced project planning with Primavera P6.",
    duration: "6 weeks",
    level: "Intermediate",
    category: "Engineering & CAD",
    image: "/images/courses/primavera.jpg",
    icon: Wrench,
    color: "from-green-500 to-emerald-600",
  },

  // Interior Design detailed items (from first image)
  {
    title: "Interior Design Theory",
    description: "Principles of interior design, color, space, and furniture planning.",
    duration: "6 weeks",
    level: "Beginner",
    category: "CADD NEST Courses",
    image: "/images/courses/interior-design-theory.jpg",
    icon: Palette,
    color: "from-purple-500 to-pink-600",
  },
  {
    title: "Masters in Interior Design",
    description: "Advanced design studio, professional practice, and portfolio.",
    duration: "24 weeks",
    level: "Advanced",
    category: "CADD NEST Courses",
    image: "/images/courses/masters-interior-design.jpg",
    icon: Palette,
    color: "from-indigo-500 to-violet-600",
  },
  {
    title: "SketchUp for Interior Design",
    description: "Rapid interior modeling workflows in SketchUp.",
    duration: "4 weeks",
    level: "Beginner",
    category: "CADD NEST Courses",
    image: "/images/courses/sketchup-interior.jpg",
    icon: Palette,
    color: "from-pink-500 to-rose-600",
  },
  {
    title: "Photoshop for Interior Design",
    description: "Rendering boards and visualizations for interiors.",
    duration: "4 weeks",
    level: "Beginner",
    category: "CADD NEST Courses",
    image: "/images/courses/photoshop-interior.jpg",
    icon: Palette,
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "AutoCAD for Interior Design",
    description: "Interior drafting standards and detailing in AutoCAD.",
    duration: "6 weeks",
    level: "Beginner",
    category: "CADD NEST Courses",
    image: "/images/courses/autocad-interior.jpg",
    icon: Palette,
    color: "from-amber-500 to-orange-600",
  },

  // Information Technology extra items (from second image)
  {
    title: "Java Full Stack Web Development",
    description: "Front‑end + Spring Boot back‑end and deployment.",
    duration: "20 weeks",
    level: "Intermediate",
    category: "IT Courses",
    image: "/java-development-programming.png",
    icon: Code,
    color: "from-orange-500 to-red-600",
  },
  {
    title: "Python Full Stack Web Development",
    description: "React/Next.js front‑end + Django/Flask back‑end.",
    duration: "20 weeks",
    level: "Intermediate",
    category: "IT Courses",
    image: "/python-development-coding.png",
    icon: Code,
    color: "from-blue-500 to-purple-600",
  },
  {
    title: "C Programming",
    description: "Programming fundamentals in C with projects.",
    duration: "6 weeks",
    level: "Beginner",
    category: "IT Courses",
    image: "/images/courses/c-programming.jpg",
    icon: Code,
    color: "from-slate-500 to-gray-600",
  },
  {
    title: "C++ Programming",
    description: "OOP, STL, and modern C++ practices.",
    duration: "8 weeks",
    level: "Beginner",
    category: "IT Courses",
    image: "/images/courses/cpp-programming.jpg",
    icon: Code,
    color: "from-sky-500 to-blue-600",
  },
  {
    title: "Basics of Computer",
    description: "Computer basics, OS, typing, internet, and productivity.",
    duration: "4 weeks",
    level: "Beginner",
    category: "IT Courses",
    image: "/images/courses/basics-of-computer.jpg",
    icon: Code,
    color: "from-emerald-500 to-green-600",
  },
  {
    title: "HTML",
    description: "Semantic markup, accessibility, and forms.",
    duration: "2 weeks",
    level: "Beginner",
    category: "IT Courses",
    image: "/images/courses/html.jpg",
    icon: Code,
    color: "from-orange-500 to-amber-600",
  },
  {
    title: "PHP",
    description: "Server‑side app development with PHP and MySQL.",
    duration: "8 weeks",
    level: "Beginner",
    category: "IT Courses",
    image: "/images/courses/php.jpg",
    icon: Code,
    color: "from-purple-500 to-indigo-600",
  },
  {
    title: "Advance Java",
    description: "Advanced Java, JDBC, JSP/Servlets, and frameworks.",
    duration: "10 weeks",
    level: "Intermediate",
    category: "IT Courses",
    image: "/images/courses/advance-java.jpg",
    icon: Code,
    color: "from-red-500 to-rose-600",
  },
  {
    title: "Core Java",
    description: "Java fundamentals, OOP, collections, and threading.",
    duration: "8 weeks",
    level: "Beginner",
    category: "IT Courses",
    image: "/images/courses/core-java.jpg",
    icon: Code,
    color: "from-yellow-500 to-amber-600",
  },

  // Our Programs (AI/Executive/Certifications) — summarized as courses
  {
    title: "Certificate in AI‑Powered Smart Product Design",
    description: "Short‑term AI‑assisted product design workflows.",
    duration: "4 weeks",
    level: "Beginner",
    category: "AI‑Powered Short‑Term Courses",
    image: "/images/courses/ai-smart-product.jpg",
    icon: Brain,
    color: "from-indigo-500 to-violet-600",
  },
  {
    title: "Certificate in AI‑Powered Smart Building Design",
    description: "AI‑assisted building concepts and analysis.",
    duration: "4 weeks",
    level: "Beginner",
    category: "AI‑Powered Short‑Term Courses",
    image: "/images/courses/ai-smart-building.jpg",
    icon: Brain,
    color: "from-blue-500 to-indigo-600",
  },

  {
    title: "Executive Diploma in Product Design",
    description: "Comprehensive diploma in product design methods and tools.",
    duration: "24 weeks",
    level: "Advanced",
    category: "Executive Diploma",
    image: "/images/courses/exec-product-design.jpg",
    icon: Palette,
    color: "from-pink-500 to-rose-600",
  },
  {
    title: "Executive Diploma in Architectural Design",
    description: "Studio‑driven architectural design with BIM.",
    duration: "24 weeks",
    level: "Advanced",
    category: "Executive Diploma",
    image: "/images/courses/exec-architectural-design.jpg",
    icon: Wrench,
    color: "from-violet-500 to-purple-600",
  },
  {
    title: "Executive Diploma in BIM",
    description: "End‑to‑end BIM workflows across disciplines.",
    duration: "24 weeks",
    level: "Advanced",
    category: "Executive Diploma",
    image: "/images/courses/exec-bim.jpg",
    icon: Wrench,
    color: "from-teal-500 to-cyan-600",
  },
  {
    title: "Executive Diploma in Interior Design",
    description: "Advanced interior design and practice.",
    duration: "24 weeks",
    level: "Advanced",
    category: "Executive Diploma",
    image: "/images/courses/exec-interior-design.jpg",
    icon: Palette,
    color: "from-purple-500 to-pink-600",
  },
  {
    title: "Executive Diploma in Structural Design",
    description: "Structural modeling, analysis, and detailing.",
    duration: "24 weeks",
    level: "Advanced",
    category: "Executive Diploma",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-fuchsia-500 to-pink-600",
  },

  {
    title: "Master Certificate in Product Design",
    description: "Advanced product design specialization.",
    duration: "16 weeks",
    level: "Advanced",
    category: "Certifications in Product Design",
    image: "/placeholder.svg?height=200&width=300",
    icon: Palette,
    color: "from-amber-500 to-orange-600",
  },
  {
    title: "Master Certificate in MEP Design",
    description: "Comprehensive MEP systems and BIM coordination.",
    duration: "16 weeks",
    level: "Advanced",
    category: "Certifications in Product Design",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-teal-500 to-cyan-600",
  },
  {
    title: "Expert Certificate in Product Design and Analysis",
    description: "Expert‑level product design with analysis.",
    duration: "12 weeks",
    level: "Advanced",
    category: "Certifications in Product Design",
    image: "/placeholder.svg?height=200&width=300",
    icon: Palette,
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "Expert Certificate in Product Design",
    description: "Hands‑on design projects and certification.",
    duration: "12 weeks",
    level: "Advanced",
    category: "Certifications in Product Design",
    image: "/placeholder.svg?height=200&width=300",
    icon: Palette,
    color: "from-violet-500 to-purple-600",
  },

  {
    title: "Master Certificate in Architecture Design",
    description: "Architectural design specialization with BIM.",
    duration: "16 weeks",
    level: "Advanced",
    category: "Certifications in AEC",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-purple-500 to-indigo-600",
  },
  {
    title: "Master Certificate in Building Design",
    description: "Building systems and design integration.",
    duration: "16 weeks",
    level: "Advanced",
    category: "Certifications in AEC",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-emerald-500 to-teal-600",
  },
  {
    title: "Master Certificate in Interior Design",
    description: "Interior design specialization with studio work.",
    duration: "16 weeks",
    level: "Advanced",
    category: "Certifications in AEC",
    image: "/placeholder.svg?height=200&width=300",
    icon: Palette,
    color: "from-pink-500 to-rose-600",
  },
  {
    title: "Master Certificate in BIM",
    description: "Advanced BIM coordination and standards.",
    duration: "16 weeks",
    level: "Advanced",
    category: "Certifications in AEC",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-sky-500 to-blue-600",
  },
  {
    title: "Expert Certificate in Architectural Design",
    description: "Expert track in architecture workflows.",
    duration: "12 weeks",
    level: "Advanced",
    category: "Certifications in AEC",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-indigo-500 to-violet-600",
  },
  {
    title: "Expert Certificate in Building Design",
    description: "Expert track in building design and services.",
    duration: "12 weeks",
    level: "Advanced",
    category: "Certifications in AEC",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "Expert Certificate in Interior Design",
    description: "Expert track in interior design.",
    duration: "12 weeks",
    level: "Advanced",
    category: "Certifications in AEC",
    image: "/placeholder.svg?height=200&width=300",
    icon: Palette,
    color: "from-rose-500 to-pink-600",
  },
  {
    title: "Expert Certificate in BIM",
    description: "Expert coordination and BIM execution plans.",
    duration: "12 weeks",
    level: "Advanced",
    category: "Certifications in AEC",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-cyan-500 to-blue-600",
  },

  {
    title: "Master Certificate in Electric Vehicle Technology",
    description: "EV systems, batteries, BMS, and charging.",
    duration: "16 weeks",
    level: "Advanced",
    category: "Certifications in Electric Vehicles",
    image: "/placeholder.svg?height=200&width=300",
    icon: Wrench,
    color: "from-amber-500 to-orange-600",
  },

  {
    title: "Python for Professionals",
    description: "Applied Python for working professionals.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Certifications in Information Technology",
    image: "/python-development-coding.png",
    icon: Code,
    color: "from-blue-500 to-indigo-600",
  },
  {
    title: "Java for Professionals",
    description: "Industry‑focused Java programming track.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Certifications in Information Technology",
    image: "/java-development-programming.png",
    icon: Code,
    color: "from-orange-500 to-red-600",
  },
  {
    title: "Data Analytics for Professionals",
    description: "Business analytics, dashboards, and insights.",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Certifications in Information Technology",
    image: "/data-analytics-dashboard.png",
    icon: Brain,
    color: "from-green-500 to-emerald-600",
  },

  // Existing flagship items to keep broad groups populated
  {
    title: "Full Stack Python Development",
    description: "Master Python web development with Django, Flask, and modern frameworks",
    duration: "16 weeks",
    level: "Intermediate",
    category: "IT & Development",
    image: "/python-development-coding.png",
    icon: Code,
    color: "from-blue-500 to-purple-600",
  },
  {
    title: "Full Stack Java Development",
    description: "Complete Java development including Spring Boot and enterprise applications",
    duration: "18 weeks",
    level: "Intermediate",
    category: "IT & Development",
    image: "/java-development-programming.png",
    icon: Code,
    color: "from-orange-500 to-red-600",
  },
  {
    title: "Python Web Development",
    description: "Specialized Python web development with modern frameworks and tools",
    duration: "12 weeks",
    level: "Beginner",
    category: "IT & Development",
    image: "/python-web-development.png",
    icon: Code,
    color: "from-indigo-500 to-purple-600",
  },
  {
    title: "Cyber Security",
    description: "Learn ethical hacking, network security, and cybersecurity fundamentals",
    duration: "16 weeks",
    level: "Advanced",
    category: "IT & Development",
    image: "/cybersecurity-training.png",
    icon: Code,
    color: "from-red-500 to-pink-600",
  },
  {
    title: "Data Science with Python",
    description: "Master data analysis, machine learning, and statistical modeling with Python",
    duration: "20 weeks",
    level: "Advanced",
    category: "Data & Analytics",
    image: "/data-science-python.png",
    icon: Brain,
    color: "from-emerald-500 to-teal-600",
  },
  {
    title: "Data Science",
    description: "Statistics, data wrangling, modeling, and ML foundations.",
    duration: "16 weeks",
    level: "Advanced",
    category: "Data & Analytics",
    image: "/placeholder.svg?height=200&width=300",
    icon: Brain,
    color: "from-indigo-500 to-violet-600",
  },
  {
    title: "Data Analytics",
    description: "Transform raw data into actionable insights using modern analytics tools",
    duration: "14 weeks",
    level: "Intermediate",
    category: "Data & Analytics",
    image: "/data-analytics-dashboard.png",
    icon: Brain,
    color: "from-cyan-500 to-blue-600",
  },
  {
    title: "Power BI",
    description: "Create interactive dashboards and business intelligence reports",
    duration: "8 weeks",
    level: "Intermediate",
    category: "Data & Analytics",
    image: "/power-bi-dashboard.png",
    icon: Brain,
    color: "from-yellow-500 to-orange-600",
  },
  {
    title: "Machine Learning & AI",
    description: "Build intelligent systems using ML algorithms and AI frameworks",
    duration: "18 weeks",
    level: "Advanced",
    category: "Data & Analytics",
    image: "/machine-learning-ai.png",
    icon: Brain,
    color: "from-violet-500 to-purple-600",
  },
]
